language: python
python:
  - "2.7"
  - "2.6"

install:
  - "pip install pycurl"
  - "sudo useradd shinken"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install unittest2"
  - "pip install flake8"

script: 
    - nosetests -vx --with-coverage --cover-package=module
    - flake8 module --exclude logevent.py
after_success:
  coveralls

notifications:
  email: false
